### ISSUE TITLE
Add File Watching for mssql-config

### ISSUE THREAD

**Issue by alecrajeev** [newrelic/nri-mssql#71]
## Is your feature request related to a problem? Please describe.
When I update the mssql-config.yml file, the agent does not automatically reflect this change. I have to restart the agent in order for the change to take effect.

## Feature Description
A file watch should be added to nri-mssql, so that when mssql-config.yml updates with a new instance, it will automatically detect the change and implement this change.

## Describe Alternatives
Currently I am working on a solution to automatically restart the pod when a config update occurs, but this is a bit of a work around.

## Additional context
My environment is fairly dynamic and we have new sql server instances on a daily basis that need to automatically get added to the monitoring.

## Priority
Nice to Have

**Comment by gsanchezgavier** [comment]
Hi @alecrajeev thanks for your time on submitting this issue.  

This is the expected behavior of the Infrastructure Agent when using the [standard configuration](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-standard-configuration-format/) files for integrations. 

We are currently working to move this config files samples  to the [new format](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format/) which have a few nice new features like hot reloading.

On the mean time you can follow [this docs](https://docs.newrelic.com/docs/create-integrations/infrastructure-integrations-sdk/specifications/host-integrations-newer-configuration-format/#update) in order to configure the integration using the new config files format.

**Comment by alecrajeev** [comment]
thanks for the help @gsanchezgavier! The new format worked great!
