### ISSUE TITLE
Support Query Plans via custom query and push to NR Log API

### ISSUE THREAD

**Issue by msummers-nr** [newrelic/nri-mssql#83]
Provide the ability to pull Query Plans from SQL Server via a custom query and push to New Relic's Log API.

The returned Query Plans can be very large, exceeding the limits of metrics or events, hence the use of the Log API with its much larger limits.

**Comment by gsanchezgavier** [comment]
Hi @msummers-nr  thanks for submitting the FR.

Just some thoughts about this FR:

I think that the integration should be capable of retrieving this data from the SQL Server with a similar mechanism as the current custom metrics. 

But on the other hand I'm not sure that the integration should be responsible for pushing this to the Log API, in the current arch the integration just send a payload to the Infra Agent which is responsible to send the Data to NR. AFAIK logs are not supported on the integrations protocol so we might need to implement this in order to support this FR.

**Comment by msummers-nr** [comment]
@gsanchezgavier It is basically the same input mechanism (custom query) but with a different output target (Logs) due to the size of the query plans.

If there's a more "Infra" way of doing this I'm all for it, we had an immediate customer need which is why this was done.

Thanks for your feedback.

**Comment by roobre** [comment]
For more context see our comment in the PR: https://github.com/newrelic/nri-mssql/pull/84#issuecomment-1013156934
